-- ============================================================================
-- Схема БД для PostgreSQL
-- ООО «МехЗемСтрой»
-- ============================================================================
BEGIN;

DROP TABLE IF EXISTS repair_assignments CASCADE;
DROP TABLE IF EXISTS monthly_repair_plan CASCADE;
DROP TABLE IF EXISTS brigade_availability CASCADE;
DROP TABLE IF EXISTS brigades CASCADE;
DROP TABLE IF EXISTS material_demand CASCADE;
DROP TABLE IF EXISTS material_norms CASCADE;
DROP TABLE IF EXISTS repair_plan CASCADE;
DROP TABLE IF EXISTS monthly_resources CASCADE;
DROP TABLE IF EXISTS repair_tech_cards CASCADE;
DROP TABLE IF EXISTS repair_requests CASCADE;
DROP TABLE IF EXISTS repair_acts CASCADE;
DROP TABLE IF EXISTS machine_events CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS machines CASCADE;

-- ============================================================================
-- 1. Справочник единиц измерения
-- ============================================================================
CREATE TABLE units (
    unit_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_symbol  VARCHAR(20)  NOT NULL UNIQUE,
    unit_name    VARCHAR(100) NOT NULL
);

INSERT INTO units (unit_symbol, unit_name) VALUES
('шт', 'штука'),
('кг', 'килограмм'),
('л',  'литр'),
('м',  'метр'),
('компл', 'комплект'),
('ч',  'час');

-- ============================================================================
-- 2. Справочник машин и механизмов
-- ============================================================================
CREATE TABLE machines (
    machine_id       VARCHAR(20) PRIMARY KEY,
    model            VARCHAR(100) NOT NULL,
    plate_number     VARCHAR(20),
    serial_number    VARCHAR(50),
    commission_year  SMALLINT CHECK (commission_year IS NULL OR commission_year BETWEEN 1900 AND 2100),
    notes            TEXT
);

-- ============================================================================
-- 3. Путевые листы / события эксплуатации
-- ============================================================================
CREATE TABLE machine_events (
    event_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_date        DATE NOT NULL,
    machine_id        VARCHAR(20) NOT NULL,
    driver_name       VARCHAR(100),
    work_object       VARCHAR(100),
    start_hours       INTEGER CHECK (start_hours IS NULL OR start_hours >= 0),
    end_hours         INTEGER CHECK (end_hours IS NULL OR end_hours >= 0),
    operation_status   VARCHAR(50),
    location          VARCHAR(100),
    technical_notes   VARCHAR(20) NOT NULL CHECK (technical_notes IN ('исправна', 'неисправна')),
    CONSTRAINT fk_machine_events_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_machine_events_machine_date
    ON machine_events (machine_id, event_date DESC, event_id DESC);

-- ============================================================================
-- 4. Акты приемки-сдачи машины после ремонта
-- ============================================================================
CREATE TABLE repair_acts (
    repair_act_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id      VARCHAR(20) NOT NULL,
    repair_type     VARCHAR(50) NOT NULL,
    start_date      DATE,
    end_date        DATE NOT NULL,
    hours_before    INTEGER CHECK (hours_before IS NULL OR hours_before >= 0),
    hours_after     INTEGER CHECK (hours_after IS NULL OR hours_after >= 0),
    conclusion      VARCHAR(20) NOT NULL CHECK (conclusion IN ('исправна', 'неисправна')),
    CONSTRAINT fk_repair_acts_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_repair_acts_machine_enddate
    ON repair_acts (machine_id, end_date DESC, repair_act_id DESC);

-- ============================================================================
-- 5. Реестр заявок на ремонт
-- ============================================================================
CREATE TABLE repair_requests (
    request_id               VARCHAR(20) PRIMARY KEY,
    request_status           VARCHAR(20) NOT NULL CHECK (request_status IN ('новая', 'в работе', 'согласована', 'отклонена', 'выполнена')),
    machine_id               VARCHAR(20) NOT NULL,
    model                    VARCHAR(100) NOT NULL,
    priority_weight          INTEGER NOT NULL CHECK (priority_weight >= 0),
    motohours_at_request     INTEGER CHECK (motohours_at_request IS NULL OR motohours_at_request >= 0),
    forecast_cost            NUMERIC(12,2),
    repair_type              VARCHAR(50) NOT NULL,
    critical_parts_required  VARCHAR(3) NOT NULL CHECK (critical_parts_required IN ('да', 'нет')),
    required_qualification   SMALLINT NOT NULL CHECK (required_qualification BETWEEN 1 AND 10),
    desired_month            SMALLINT CHECK (desired_month IS NULL OR desired_month BETWEEN 1 AND 12),
    notes                    TEXT,
    CONSTRAINT fk_repair_requests_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_repair_requests_status_priority
    ON repair_requests (request_status, priority_weight DESC, desired_month);

-- ============================================================================
-- 6. Технологические карты ремонтных операций
-- ============================================================================
CREATE TABLE repair_tech_cards (
    techcard_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_type               VARCHAR(50) NOT NULL,
    machine_id                VARCHAR(20) NOT NULL,
    labor_hours               INTEGER NOT NULL CHECK (labor_hours >= 0),
    required_qualification    SMALLINT NOT NULL CHECK (required_qualification BETWEEN 1 AND 10),
    operations_description    TEXT,
    notes                     TEXT,
    CONSTRAINT fk_repair_tech_cards_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT unique_repair_machine UNIQUE (repair_type, machine_id)
);

-- ============================================================================
-- 7. Ресурсы и наличие запчастей по месяцам
-- ============================================================================
CREATE TABLE monthly_resources (
    resource_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_no                SMALLINT NOT NULL UNIQUE CHECK (month_no BETWEEN 1 AND 12),
    available_hours         INTEGER CHECK (available_hours IS NULL OR available_hours >= 0),
    budget                  NUMERIC(12,2),
    max_units_in_repair     INTEGER CHECK (max_units_in_repair IS NULL OR max_units_in_repair >= 0),
    critical_parts_available VARCHAR(3) NOT NULL CHECK (critical_parts_available IN ('да', 'нет')),
    notes                   TEXT
);

-- ============================================================================
-- 8. Годовой план ремонтов
-- ============================================================================
CREATE TABLE repair_plan (
    plan_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id              VARCHAR(20) NOT NULL UNIQUE,
    machine_id              VARCHAR(20) NOT NULL,
    model                   VARCHAR(100) NOT NULL,
    repair_type             VARCHAR(50) NOT NULL,
    required_qualification  SMALLINT NOT NULL CHECK (required_qualification BETWEEN 1 AND 10),
    labor_hours             INTEGER NOT NULL CHECK (labor_hours >= 0),
    priority_weight         INTEGER NOT NULL CHECK (priority_weight >= 0),
    forecast_cost           NUMERIC(12,2),
    assigned_month          SMALLINT CHECK (assigned_month IS NULL OR assigned_month BETWEEN 1 AND 12),
    CONSTRAINT fk_repair_plan_request
        FOREIGN KEY (request_id) REFERENCES repair_requests(request_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_repair_plan_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_repair_plan_machine_month
    ON repair_plan (machine_id, assigned_month);

-- ============================================================================
-- 9. Справочник материалов и запасных частей
-- ============================================================================
CREATE TABLE materials (
    material_code   VARCHAR(20) PRIMARY KEY,
    material_name   VARCHAR(200) NOT NULL,
    unit_id         INTEGER NOT NULL,
    CONSTRAINT fk_material_unit
        FOREIGN KEY (unit_id) REFERENCES units(unit_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO materials (material_code, material_name, unit_id) VALUES
('MAT-001', 'Масло моторное 10W-40', 3),
('MAT-002', 'Масло гидравлическое', 3),
('MAT-003', 'Фильтр масляный', 1),
('MAT-004', 'Фильтр воздушный', 1),
('MAT-005', 'Смазка литиевая', 2),
('MAT-006', 'Ремень приводной', 1),
('MAT-007', 'Прокладка', 1),
('MAT-008', 'Болт крепежный', 1),
('MAT-009', 'Гайка крепежная', 1),
('MAT-010', 'Шайба плоская', 1);

-- ============================================================================
-- 10. Нормативные карты ремонта
-- ============================================================================
CREATE TABLE material_norms (
    norm_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_type             VARCHAR(50) NOT NULL,
    model                   VARCHAR(100) NOT NULL,
    material_code           VARCHAR(20) NOT NULL,
    consumption_per_repair  NUMERIC(10,3) NOT NULL CHECK (consumption_per_repair >= 0),
    CONSTRAINT fk_material_norms_material
        FOREIGN KEY (material_code) REFERENCES materials(material_code)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT unique_norm UNIQUE (repair_type, model, material_code)
);

CREATE INDEX idx_material_norms_repair_model
    ON material_norms (repair_type, model);

-- ============================================================================
-- 11. Ведомость потребности материалов
-- ============================================================================
CREATE TABLE material_demand (
    demand_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_month      SMALLINT NOT NULL CHECK (target_month BETWEEN 1 AND 12),
    material_code     VARCHAR(20) NOT NULL,
    demand_quantity   NUMERIC(10,3) NOT NULL CHECK (demand_quantity >= 0),
    notes             TEXT,
    CONSTRAINT fk_material_demand_material
        FOREIGN KEY (material_code) REFERENCES materials(material_code)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT unique_demand UNIQUE (target_month, material_code)
);

-- ============================================================================
-- 12. Справочник бригад
-- ============================================================================
CREATE TABLE brigades (
    brigade_number   VARCHAR(20) PRIMARY KEY,
    team_composition TEXT NOT NULL,
    specialization   VARCHAR(20) NOT NULL CHECK (specialization IN ('слесарь', 'электрик', 'сварщик', 'универсальная')),
    qualification    SMALLINT NOT NULL CHECK (qualification BETWEEN 1 AND 10),
    contact          VARCHAR(50),
    notes            TEXT
);

-- ============================================================================
-- 13. График занятости бригад
-- ============================================================================
CREATE TABLE brigade_availability (
    availability_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brigade_number          VARCHAR(20) NOT NULL,
    available_start         DATE NOT NULL,
    available_end           DATE NOT NULL,
    available_hours         INTEGER CHECK (available_hours IS NULL OR available_hours >= 0),
    current_assigned_hours  INTEGER NOT NULL DEFAULT 0 CHECK (current_assigned_hours >= 0),
    contact                 VARCHAR(50),
    notes                   TEXT,
    CONSTRAINT fk_brigade_availability_brigade
        FOREIGN KEY (brigade_number) REFERENCES brigades(brigade_number)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_availability_dates CHECK (available_end >= available_start),
    CONSTRAINT chk_availability_hours CHECK (
        available_hours IS NULL OR current_assigned_hours <= available_hours
    )
);

CREATE INDEX idx_brigade_availability_period
    ON brigade_availability (brigade_number, available_start, available_end);

-- ============================================================================
-- 14. Месячный план ремонтов
-- ============================================================================
CREATE TABLE monthly_repair_plan (
    monthly_plan_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id               VARCHAR(20) NOT NULL UNIQUE,
    machine_id               VARCHAR(20) NOT NULL,
    model                    VARCHAR(100) NOT NULL,
    repair_type              VARCHAR(50) NOT NULL,
    required_specialization  VARCHAR(20) NOT NULL CHECK (required_specialization IN ('слесарь', 'электрик', 'сварщик', 'универсальная')),
    required_qualification   SMALLINT NOT NULL CHECK (required_qualification BETWEEN 1 AND 10),
    planned_start_date       DATE,
    planned_end_date         DATE,
    labor_hours              INTEGER NOT NULL CHECK (labor_hours >= 0),
    priority_weight          INTEGER NOT NULL CHECK (priority_weight >= 0),
    readiness_status         VARCHAR(20) NOT NULL CHECK (readiness_status IN ('готова', 'не готова')),
    notes                    TEXT,
    CONSTRAINT fk_monthly_repair_plan_request
        FOREIGN KEY (request_id) REFERENCES repair_requests(request_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_monthly_repair_plan_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_monthly_repair_plan_priority
    ON monthly_repair_plan (priority_weight DESC, planned_start_date, request_id);

-- ============================================================================
-- 15. Распределение бригад на ремонты
-- ============================================================================
CREATE TABLE repair_assignments (
    assignment_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          VARCHAR(20) NOT NULL UNIQUE,
    machine_id          VARCHAR(20) NOT NULL,
    start_date          DATE,
    end_date            DATE,
    brigade_number      VARCHAR(20),
    planned_hours       INTEGER CHECK (planned_hours IS NULL OR planned_hours >= 0),
    responsible_person  VARCHAR(100),
    assignment_status   VARCHAR(20) NOT NULL CHECK (assignment_status IN ('назначена', 'не назначена')),
    notes               TEXT,
    CONSTRAINT fk_repair_assignments_request
        FOREIGN KEY (request_id) REFERENCES repair_requests(request_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_repair_assignments_machine
        FOREIGN KEY (machine_id) REFERENCES machines(machine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_repair_assignments_brigade
        FOREIGN KEY (brigade_number) REFERENCES brigades(brigade_number)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

COMMIT;